### ISSUE TITLE
Error running OAuth2Service.ConsoleApp

### ISSUE THREAD

**Issue by RandyLyne** [Digi-Key/ApiClient.V3#3]
Im attempting to test the API following the readme instructions.
I get the following error.

System.Net.Http.HttpRequestException was unhandled
Message: An unhandled exception of type 'System.Net.Http.HttpRequestException' occurred in mscorlib.dll
Additional information: An error occurred while sending the request.

**Comment by RandyLyne** [comment]
Fixed by placing "ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;" into "public async Task<OAuth2AccessToken> FinishAuthorization(string code)" in OAuth2Service.cs

**Comment by RandyLyne** [comment]
Please update fix main code.

**Comment by michael-block** [comment]
This is now merged in master..
